# Try building on both Linux and macOS platforms

name: Build

on: [push, pull_request]

jobs:
  linux:
    name: Linux Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang++-7, clang++-8, clang++-9, clang++-10, clang++-11, g++-7, g++-8, g++-9, g++-10]
    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: sudo apt install ${{ matrix.cpp-version }} libeigen3-dev coreutils

      - name: Configure
        run:  cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/${{ matrix.compiler }}

      - name: Build
        run: cmake --build build --config Release -j $(nproc)
  
  macOS:
    name: macOS Release
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: brew install eigen coreutils

      - name: Configure
        run:  cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j $(nproc)