name: Code Coverage

on: [push, pull_request]

jobs:
  gather-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: sudo apt install libeigen3-dev coreutils lcov

      - name: Configure
        run:  cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"

      - name: Build
        run: cmake --build build -j $(nproc)

      - name: Tests
        working-directory: build/
        run: ctest -C Debug -T test -E "benchmarks" -T Coverage -j $(nproc) 

      - name: Code coverage
        if: always()
        working-directory: build/
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*tests/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Publish to codecov
        if: always()
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ runner.os }}
          name: ${{ runner.os }}-coverage
          files: ./build/coverage.info
