name: Code Coverage

on: [push, pull_request]

jobs:
  code_coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: sudo apt install libeigen3-dev coreutils

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
    - name: Build
      run: cmake --build build/ --config Debug

    - name: Collect code coverage
      working-directory: build/
      run: bash <(curl -s https://codecov.io/bash)
