# Test the library

name: Test

on: [push, pull_request]

# env:
#   CTEST_OUTPUT_ON_FAILURE: ON
#   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  ####################
  # Linux / macOS
  ####################

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: sudo apt install libeigen3-dev coreutils lcov

      - name: Configure
        run:  cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"

      - name: Build
        run: cmake --build build -j $(nproc)

      - name: Tests
        working-directory: build/
        run: ctest -C Debug -T test -E "benchmarks|check_finite_differences" -T Coverage -j $(nproc) 

      - name: Code coverage
        working-directory: build/
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*tests/*' --output-file coverage.info
          lcov --list coverage.info
          bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
